# words for the hangman game

words = ("cat","dog","cow","horse","sheep","goat","pig","rabbit","mouse","rat","lion","tiger","elephant","giraffe","zebra","monkey","gorilla","bear","wolf","fox",
"deer","kangaroo","koala","panda","camel","donkey","hamster","squirrel","hedgehog","bat",
"chicken","duck","goose","turkey","eagle","hawk","owl","parrot","pigeon","sparrow",
"fish","shark","dolphin","whale","octopus","turtle","snake","lizard","frog","crocodile",
"apple","banana","orange","pear","grape","melon","lemon","peach","plum","cherry",
"bread","butter","cheese","milk","yogurt","cream","egg","omelet","pizza","burger",
"sandwich","pasta","noodle","rice","soup","salad","steak","sausage","bacon",
"sushi","kebab","falafel","hummus","cake","cookie","biscuit","chocolate","candy",
"sugar","honey","jam","icecream","dessert","coffee","tea","juice","water","soda",
"lemonade","smoothie","cereal","oats","corn","potato","tomato","onion","garlic",
"pepper","carrot","cabbage","lettuce","spinach","bean","lentil","pea","chickpea",
"mushroom","olive","oil","vinegar","salt","spice","herb","table","chair","desk","sofa","bed","pillow","blanket","lamp","clock","mirror",
"window","door","floor","ceiling","wall","roof","stairs","shelf","drawer","cabinet",
"plate","bowl","cup","glass","fork","knife","spoon","pan","pot","kettle",
"fridge","freezer","oven","toaster","microwave","blender","mixer","scale","timer",
"sink","soap","towel","shampoo","brush","comb","toothpaste","razor","bucket",
"broom","mop","vacuum","detergent","sponge","cloth","basket","hanger","iron","fan",
"remote","screen","monitor","keyboard","mousepad","printer","router","speaker","camera",
"phone","charger","cable","battery","tablet","laptop","notebook","pencil","eraser",
"marker","folder","paper","envelope","stamp","scissors","glue","tape","ruler",
"calculator","backpack","wallet","purse","key","lock","umbrella","watch","ring",
"bracelet","necklace","belt","shoe","sock","jacket","shirt","trousers","jeans",
"sweater","scarf","hat","cap","glove","time","day","week","month","year","morning","evening","night","today","tomorrow",
"yesterday","moment","hour","minute","second","place","home","school","office",
"market","street","city","village","country","world","people","person","family",
"friend","group","child","parent","teacher","student","worker","leader","member",
"player","writer","reader","idea","thought","dream","plan","goal","problem",
"solution","answer","question","story","fact","truth","reason","example","result",
"change","choice","chance","luck","hope","love","peace","order","power","money",
"price","value","cost","sale","trade","work","job","task","effort","skill","talent",
"habit","rule","law","system","game","sport","music","sound","voice","image",
"picture","color","shape","size","speed","energy","force","light","shadow","heat",
"cold","weather","season","nature","river","lake","sea","beach","forest","field",
"mountain","valley","island","desert")
